import { GeistMono } from 'geist/font/mono';
import { GeistSans } from "geist/font/sans";

import type { PropsWithChildren } from "react";
import { TanstackProvider } from '~/components/providers/TanstackProvider';
import { ThemeProvider } from "~/components/providers/ThemeProvider";
import UserSessionProvider from "~/components/providers/UserSessionProvider";
import { getServerAuthSession } from "~/server/auth";
import "~/styles/globals.css";

export const metadata = {
  title: "T3Trainer",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: PropsWithChildren) {
  const session = await getServerAuthSession();

    return (
      <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`} suppressHydrationWarning>
        <body>
          <TanstackProvider>
            <UserSessionProvider session={session}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <main className='flex h-screen'>
                  {children}
                </main>
              </ThemeProvider>
            </UserSessionProvider>
          </TanstackProvider>
        </body>
      </html>
    );
  }
