import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { GeistSans } from "geist/font/sans";
import type { PropsWithChildren } from "react";
import Provider from "~/components/providers/Provider";
import { ThemeProvider } from "~/components/providers/ThemeProvider";
import { getServerAuthSession } from "~/server/auth";
import "~/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: PropsWithChildren) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body>
          <Provider session={session}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </Provider>

      </body>
    </html>
  );
}
